WIP : Adding  Java app

diff --git a/03-configure-private-registry/check-kubernetes-vm b/03-configure-private-registry/check-kubernetes-vm
--- a/03-configure-private-registry/check-kubernetes-vm
+++ b/03-configure-private-registry/check-kubernetes-vm
@@ -1,7 +1,12 @@
-#!/bin/bash
+#!/usr/bin/env bash
+eval "$(direnv export bash)"
+
+set -euxo pipefail
+
+direnv allow .
 
 # login to docker private registry 
-( echo -n "admin123" | docker login localhost:31081 --password-stdin ) || fail-message "unable to login to Docker registry"
+( echo -n "${IMAGE_REGISTRY_PASSWORD}" | docker login localhost:31081 --username "${IMAGE_REGISTRY_USER}" --password-stdin ) || fail-message "unable to login to Docker registry"
 
 # Docker push
 (docker pull gcr.io/google-samples/hello-app:1.0;docker tag gcr.io/google-samples/hello-app:1.0 "localhost:31081/hello-app:1.0";docker push "localhost:31081/hello-app:1.0") || fail-message "Unable to push image to the private registry"
